# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ItaliaCandele - Candele Profumate di Qualità
email: info@italiacandele.com
description: "ItaliaCandele è il tuo negozio online per candele profumate, artigianali e di alta qualità. Scopri fragranze uniche per ogni ambiente e momento della giornata."
keywords: "ItaliaCandele, candele profumate, candele artigianali, fragranze, ambiente accogliente, regali"
author: "Antonio Trento"
og_image: "ItaliaCandele-og-image.jpg"  # Immagine da utilizzare per Open Graph e Twitter Cards
locale: "it_IT"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://italiacandele.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ItaliaCandele
github_username:  ItaliaCandele
snipchart: YWFiZDYzMzYtZjY3MC00ZDliLTgwNWUtMGFlY2IyOWQ0Y2Q2NjM2NDcxMTc3NTMxNjE4MDUw

collections:
  products:
    output: true
    permalink: /prodotti/:title/



# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
